spring:
  datasource:
    url: jdbc:mysql://10.4.18.100:3306/hqtest?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true #打印sql
    properties:
      hibernate:
        format_sql: true
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.hq.entity