server:
  port: 8010
spring:
  application:
    name: provider # Note: 在Eureka中的名字
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    instance:
      prefer-ip-address: true # Note：是否把ip地址也注册进来