server:
  port: 8090
spring:
  application:
    name: zipkinclient
  sleuth:
    web:
      client:
        enabled: true #Note: 启动web客户端
    sampler:
      probability: 1.0 #Note：采样比例
  zipkin:
    base-url: http://localhost:9090/ #Note：配置服务端
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
