server:
  port: 8762
spring:
  application:
    name: nativeconfigserver
  profiles:
    active: native #Note：配置文件的存储方式是本地的，相对远程的git来说的
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared #Note: 所有的远程配置，都放在shared目录下